package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

var (
	typeFlag   = flag.String("type", "", "Type name to generate serde for")
	outputFlag = flag.String("output", "", "Output file path")
	dirFlag    = flag.String("dir", ".", "Directory containing the type to parse")
)

func main() {
	flag.Parse()

	if *typeFlag == "" {
		log.Fatal("must specify -type flag")
	}
	if *outputFlag == "" {
		log.Fatal("must specify -output flag")
	}

	// Parse the specified package directory
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, *dirFlag, nil, 0)
	if err != nil {
		log.Fatalf("failed to parse package: %v", err)
	}

	// Find the target type (struct or alias)
	var structType *ast.StructType
	var aliasType string // underlying type if this is an alias
	var pkgName string

	for name, pkg := range pkgs {
		pkgName = name
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec := spec.(*ast.TypeSpec)
					if typeSpec.Name.Name == *typeFlag {
						// struct or alias
						if st, ok := typeSpec.Type.(*ast.StructType); ok {
							structType = st
						} else if ident, ok := typeSpec.Type.(*ast.Ident); ok {
							aliasType = ident.Name
						}
						break
					}
				}
			}
		}
	}

	if structType == nil && aliasType == "" {
		log.Fatalf("could not find type %s", *typeFlag)
	}

	qualifiedType := *typeFlag
	// do not prefix the name with "message." since we're generating for the message package
	if pkgName != "message" {
		qualifiedType = pkgName + "." + *typeFlag
	}

	// Generate code
	var code string
	if structType != nil {
		code = generateStructSerializer(*typeFlag, pkgName, structType, qualifiedType)
	} else {
		code = generateAliasSerializer(*typeFlag, pkgName, qualifiedType)
	}

	// Write output
	if err := os.WriteFile(*outputFlag, []byte(code), 0644); err != nil {
		log.Fatalf("failed to write output: %v", err)
	}

	fmt.Printf("Generated serializer for %s in %s\n", *typeFlag, *outputFlag)
}

func generateStructSerializer(typeName, pkgName string, structType *ast.StructType, qualifiedType string) string {
	var builder strings.Builder

	// Determine which imports are needed
	neededImports := make(map[string]bool)

	for _, field := range structType.Fields.List {
		// If it's a slice, we need to import the element's package
		if isSliceType(field.Type) {
			elemType, _ := getSliceElementType(field.Type)
			cleanElem := strings.TrimPrefix(elemType, "*")

			if strings.Contains(cleanElem, ".") {
				parts := strings.Split(cleanElem, ".")
				if len(parts) >= 2 {
					pkg := parts[0]
					neededImports[pkg] = true
				}
			}
		}
	}
	// need the package of the struct obviously
	neededImports[pkgName] = true
	// never need meesage since we're generating for message
	delete(neededImports, "message")

	// Header
	builder.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	builder.WriteString("package message\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"io\"\n")

	if len(neededImports) > 0 {
		builder.WriteString("\n")
		for pkg := range neededImports {
			builder.WriteString(fmt.Sprintf("\t\"github.com/danharasymiw/bit-rail/%s\"\n", pkg))
		}
	}

	builder.WriteString(")\n\n")
	builder.WriteString(fmt.Sprintf("func write%s(w io.Writer, v *%s) error {\n", typeName, qualifiedType))

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fieldName := name.Name
			fieldType := getTypeName(field.Type)

			if fieldType == "string" {
				// String type - write length, then string
				builder.WriteString(fmt.Sprintf("\tif err := writeString(w, v.%s); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"unable to serialize %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
			} else if fieldType == "uuid.UUID" {
				// UUID type - use our own functions
				builder.WriteString(fmt.Sprintf("\tif err := writeUUID(w, &v.%s); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"error writing %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
			} else if isSliceType(field.Type) {
				// Slice type - write length, then loop
				elemType, _ := getSliceElementType(field.Type)
				serializerName := getSerializerName(elemType)

				builder.WriteString(fmt.Sprintf("\tif len(v.%s) > 65535 {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"%s slice too long: %%d\", len(v.%s))\n", fieldName, fieldName))
				builder.WriteString("\t}\n")
				builder.WriteString(fmt.Sprintf("\tif err := binaryWrite(w, uint16(len(v.%s))); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"error writing %s length: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
				builder.WriteString(fmt.Sprintf("\tfor _, elem := range v.%s {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\tif err := write%s(w, elem); err != nil {\n", serializerName))
				builder.WriteString(fmt.Sprintf("\t\t\treturn fmt.Errorf(\"error writing %s element: %%v\", err)\n", fieldName))
				builder.WriteString("\t\t}\n")
				builder.WriteString("\t}\n")
			} else if isPrimitiveType(fieldType) {
				// Primitive type - use binaryWrite
				builder.WriteString(fmt.Sprintf("\tif err := binaryWrite(w, v.%s); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"error writing %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
			} else {
				// Non primitive type - call its serializer
				serializerName := getSerializerName(fieldType)
				// If field is a pointer don't add &
				fieldRef := fmt.Sprintf("&v.%s", fieldName)
				if strings.HasPrefix(fieldType, "*") {
					fieldRef = fmt.Sprintf("v.%s", fieldName)
				}
				builder.WriteString(fmt.Sprintf("\tif err := write%s(w, %s); err != nil {\n", serializerName, fieldRef))
				builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"error writing %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
			}
		}
	}

	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n\n")

	// Read function
	builder.WriteString(fmt.Sprintf("func read%s(r io.Reader) (*%s, error) {\n", typeName, qualifiedType))
	builder.WriteString(fmt.Sprintf("\tv := &%s{}\n", qualifiedType))

	for _, field := range structType.Fields.List {
		for _, name := range field.Names {
			fieldName := name.Name
			fieldType := getTypeName(field.Type)

			if fieldType == "string" {
				// String type - read length, then string
				builder.WriteString(fmt.Sprintf("\t%s, err := readString(r)\n", fieldName))
				builder.WriteString("\tif err != nil {\n")
				builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
				builder.WriteString(fmt.Sprintf("\tv.%s = %s\n", fieldName, fieldName))
			} else if fieldType == "uuid.UUID" {
				// UUID type - use our own uuid read function
				builder.WriteString(fmt.Sprintf("\t%s, err := readUUID(r)\n", fieldName))
				builder.WriteString("\tif err != nil {\n")
				builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
				builder.WriteString(fmt.Sprintf("\tv.%s = %s\n", fieldName, fieldName))
			} else if isSliceType(field.Type) {
				// Slice type - read length, then loop and read each element
				elemType, _ := getSliceElementType(field.Type)
				serializerName := getSerializerName(elemType)

				qualifiedFieldType := fieldType
				// Same package type, need to qualify it
				if !strings.Contains(fieldType, ".") && pkgName != "message" {
					qualifiedFieldType = strings.Replace(fieldType, "[]*", "[]*"+pkgName+".", 1)
				}

				builder.WriteString(fmt.Sprintf("\tvar %sLen uint16\n", fieldName))
				builder.WriteString(fmt.Sprintf("\tif err := binaryRead(r, &%sLen); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s length: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
				builder.WriteString(fmt.Sprintf("\tv.%s = make(%s, %sLen)\n", fieldName, qualifiedFieldType, fieldName))
				builder.WriteString(fmt.Sprintf("\tfor i := range v.%s {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\telem, err := read%s(r)\n", serializerName))
				builder.WriteString("\t\tif err != nil {\n")
				builder.WriteString(fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"error reading %s element: %%v\", err)\n", fieldName))
				builder.WriteString("\t\t}\n")
				builder.WriteString(fmt.Sprintf("\t\tv.%s[i] = elem\n", fieldName))
				builder.WriteString("\t}\n")
			} else if isPrimitiveType(fieldType) {
				// Primitive type - use binaryRead
				builder.WriteString(fmt.Sprintf("\tif err := binaryRead(r, &v.%s); err != nil {\n", fieldName))
				builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
			} else {
				serializerName := getSerializerName(fieldType)
				builder.WriteString(fmt.Sprintf("\t%sVal, err := read%s(r)\n", fieldName, serializerName))
				builder.WriteString("\tif err != nil {\n")
				builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s: %%v\", err)\n", fieldName))
				builder.WriteString("\t}\n")
				// If field is a pointer assign directly otherwise dereference
				if strings.HasPrefix(fieldType, "*") {
					builder.WriteString(fmt.Sprintf("\tv.%s = %sVal\n", fieldName, fieldName))
				} else {
					builder.WriteString(fmt.Sprintf("\tv.%s = *%sVal\n", fieldName, fieldName))
				}
			}
		}
	}

	builder.WriteString("\treturn v, nil\n")
	builder.WriteString("}\n")

	return builder.String()
}

func getTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", t.X.(*ast.Ident).Name, t.Sel.Name)
	case *ast.StarExpr:
		return "*" + getTypeName(t.X)
	case *ast.ArrayType:
		// Slice type
		return "[]" + getTypeName(t.Elt)
	default:
		return "unknown"
	}
}

func isSliceType(expr ast.Expr) bool {
	_, ok := expr.(*ast.ArrayType)
	return ok
}

func getSliceElementType(expr ast.Expr) (string, bool) {
	arrayType, ok := expr.(*ast.ArrayType)
	if !ok {
		return "", false
	}
	return getTypeName(arrayType.Elt), true
}

func isPrimitiveType(typeName string) bool {
	primitives := map[string]bool{
		"string": true,
		"bool":   true,
		"int":    true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"byte": true, "rune": true,
	}
	return primitives[typeName]
}

func generateAliasSerializer(typeName, pkgName, qualifiedType string) string {
	var builder strings.Builder

	// Header
	builder.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	builder.WriteString("package message\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"io\"\n")

	if pkgName != "message" {
		builder.WriteString("\n")
		builder.WriteString(fmt.Sprintf("\t\"github.com/danharasymiw/bit-rail/%s\"\n", pkgName))
	}

	builder.WriteString(")\n\n")

	// Write function for alias - just wraps binaryWrite
	builder.WriteString(fmt.Sprintf("func write%s(w io.Writer, v *%s) error {\n", typeName, qualifiedType))
	builder.WriteString("\tif err := binaryWrite(w, *v); err != nil {\n")
	builder.WriteString(fmt.Sprintf("\t\treturn fmt.Errorf(\"error writing %s: %%v\", err)\n", typeName))
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n\n")

	// Read function for alias - just wraps binaryRead
	builder.WriteString(fmt.Sprintf("func read%s(r io.Reader) (*%s, error) {\n", typeName, qualifiedType))
	builder.WriteString(fmt.Sprintf("\tvar v %s\n", qualifiedType))
	builder.WriteString("\tif err := binaryRead(r, &v); err != nil {\n")
	builder.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"error reading %s: %%v\", err)\n", typeName))
	builder.WriteString("\t}\n")
	builder.WriteString("\treturn &v, nil\n")
	builder.WriteString("}\n")

	return builder.String()
}

func getSerializerName(typeName string) string {
	// Remove package prefix for serializer name
	// "types.Tile" -> "Tile"
	// "*TrainCar" -> "TrainCar"
	typeName = strings.TrimPrefix(typeName, "*")
	parts := strings.Split(typeName, ".")
	return parts[len(parts)-1]
}
