// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func writeBlock(w io.Writer, v *types.Block) error {
	if err := writeUUID(w, &v.ID); err != nil {
		return fmt.Errorf("error writing ID: %v", err)
	}
	if err := writeUUID(w, &v.OccupiedBy); err != nil {
		return fmt.Errorf("error writing OccupiedBy: %v", err)
	}
	return nil
}

func readBlock(r io.Reader) (*types.Block, error) {
	v := &types.Block{}
	ID, err := readUUID(r)
	if err != nil {
		return nil, fmt.Errorf("error reading ID: %v", err)
	}
	v.ID = ID
	OccupiedBy, err := readUUID(r)
	if err != nil {
		return nil, fmt.Errorf("error reading OccupiedBy: %v", err)
	}
	v.OccupiedBy = OccupiedBy
	return v, nil
}
