// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"
)

func WriteChatMessage(w io.Writer, v *ChatMessage) error {
	if err := writeString(w, v.Author); err != nil {
		return fmt.Errorf("unable to serialize Author: %v", err)
	}
	if err := writeString(w, v.Message); err != nil {
		return fmt.Errorf("unable to serialize Message: %v", err)
	}
	return nil
}

func ReadChatMessage(r io.Reader) (*ChatMessage, error) {
	v := &ChatMessage{}
	Author, err := readString(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Author: %v", err)
	}
	v.Author = Author
	Message, err := readString(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Message: %v", err)
	}
	v.Message = Message
	return v, nil
}
