// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
	"github.com/danharasymiw/bit-rail/world"
)

func writeChunk(w io.Writer, v *world.Chunk) error {
	if err := writePos(w, &v.Pos); err != nil {
		return fmt.Errorf("error writing Pos: %v", err)
	}
	if len(v.Tiles) > 65535 {
		return fmt.Errorf("Tiles slice too long: %d", len(v.Tiles))
	}
	if err := binaryWrite(w, uint16(len(v.Tiles))); err != nil {
		return fmt.Errorf("error writing Tiles length: %v", err)
	}
	for _, elem := range v.Tiles {
		if err := writeTile(w, elem); err != nil {
			return fmt.Errorf("error writing Tiles element: %v", err)
		}
	}
	return nil
}

func readChunk(r io.Reader) (*world.Chunk, error) {
	v := &world.Chunk{}
	PosVal, err := readPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Pos: %v", err)
	}
	v.Pos = *PosVal
	var TilesLen uint16
	if err := binaryRead(r, &TilesLen); err != nil {
		return nil, fmt.Errorf("error reading Tiles length: %v", err)
	}
	v.Tiles = make([]*types.Tile, TilesLen)
	for i := range v.Tiles {
		elem, err := readTile(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Tiles element: %v", err)
		}
		v.Tiles[i] = elem
	}
	return v, nil
}
