// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func WriteDir(w io.Writer, v *types.Dir) error {
	if err := binaryWrite(w, uint8(*v)); err != nil {
		return fmt.Errorf("error writing Dir: %v", err)
	}
	return nil
}

func ReadDir(r io.Reader) (*types.Dir, error) {
	var raw uint8
	if err := binaryRead(r, &raw); err != nil {
		return nil, fmt.Errorf("error reading Dir: %v", err)
	}
	v := types.Dir(raw)
	return &v, nil
}
