// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/world"
	"github.com/danharasymiw/bit-rail/trains"
)

func writeInitialLoadMessage(w io.Writer, v *InitialLoadMessage) error {
	if err := binaryWrite(w, v.Width); err != nil {
		return fmt.Errorf("error writing Width: %v", err)
	}
	if err := binaryWrite(w, v.Height); err != nil {
		return fmt.Errorf("error writing Height: %v", err)
	}
	if err := writePos(w, &v.CameraPos); err != nil {
		return fmt.Errorf("error writing CameraPos: %v", err)
	}
	if len(v.Chunks) > 65535 {
		return fmt.Errorf("Chunks slice too long: %d", len(v.Chunks))
	}
	if err := binaryWrite(w, uint16(len(v.Chunks))); err != nil {
		return fmt.Errorf("error writing Chunks length: %v", err)
	}
	for _, elem := range v.Chunks {
		if err := writeChunk(w, elem); err != nil {
			return fmt.Errorf("error writing Chunks element: %v", err)
		}
	}
	if len(v.Trains) > 65535 {
		return fmt.Errorf("Trains slice too long: %d", len(v.Trains))
	}
	if err := binaryWrite(w, uint16(len(v.Trains))); err != nil {
		return fmt.Errorf("error writing Trains length: %v", err)
	}
	for _, elem := range v.Trains {
		if err := writeTrain(w, elem); err != nil {
			return fmt.Errorf("error writing Trains element: %v", err)
		}
	}
	if len(v.Tracks) > 65535 {
		return fmt.Errorf("Tracks slice too long: %d", len(v.Tracks))
	}
	if err := binaryWrite(w, uint16(len(v.Tracks))); err != nil {
		return fmt.Errorf("error writing Tracks length: %v", err)
	}
	for _, elem := range v.Tracks {
		if err := writeTrackUpdate(w, elem); err != nil {
			return fmt.Errorf("error writing Tracks element: %v", err)
		}
	}
	return nil
}

func readInitialLoadMessage(r io.Reader) (*InitialLoadMessage, error) {
	v := &InitialLoadMessage{}
	if err := binaryRead(r, &v.Width); err != nil {
		return nil, fmt.Errorf("error reading Width: %v", err)
	}
	if err := binaryRead(r, &v.Height); err != nil {
		return nil, fmt.Errorf("error reading Height: %v", err)
	}
	CameraPosVal, err := readPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading CameraPos: %v", err)
	}
	v.CameraPos = *CameraPosVal
	var ChunksLen uint16
	if err := binaryRead(r, &ChunksLen); err != nil {
		return nil, fmt.Errorf("error reading Chunks length: %v", err)
	}
	v.Chunks = make([]*world.Chunk, ChunksLen)
	for i := range v.Chunks {
		elem, err := readChunk(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Chunks element: %v", err)
		}
		v.Chunks[i] = elem
	}
	var TrainsLen uint16
	if err := binaryRead(r, &TrainsLen); err != nil {
		return nil, fmt.Errorf("error reading Trains length: %v", err)
	}
	v.Trains = make([]*trains.Train, TrainsLen)
	for i := range v.Trains {
		elem, err := readTrain(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Trains element: %v", err)
		}
		v.Trains[i] = elem
	}
	var TracksLen uint16
	if err := binaryRead(r, &TracksLen); err != nil {
		return nil, fmt.Errorf("error reading Tracks length: %v", err)
	}
	v.Tracks = make([]*TrackUpdate, TracksLen)
	for i := range v.Tracks {
		elem, err := readTrackUpdate(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Tracks element: %v", err)
		}
		v.Tracks[i] = elem
	}
	return v, nil
}
