// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/trains"
	"github.com/danharasymiw/bit-rail/world"
)

func WriteInitialLoadMessage(w io.Writer, v *InitialLoadMessage) error {
	if v.Width < 0 || v.Width > 65535 {
		return fmt.Errorf("Width out of uint16 range: %d", v.Width)
	}
	if err := binaryWrite(w, uint16(v.Width)); err != nil {
		return fmt.Errorf("error writing Width: %v", err)
	}
	if v.Height < 0 || v.Height > 65535 {
		return fmt.Errorf("Height out of uint16 range: %d", v.Height)
	}
	if err := binaryWrite(w, uint16(v.Height)); err != nil {
		return fmt.Errorf("error writing Height: %v", err)
	}
	if err := WritePos(w, &v.CameraPos); err != nil {
		return fmt.Errorf("error writing CameraPos: %v", err)
	}
	if len(v.Chunks) > 65535 {
		return fmt.Errorf("Chunks slice too long: %d", len(v.Chunks))
	}
	if err := binaryWrite(w, uint16(len(v.Chunks))); err != nil {
		return fmt.Errorf("error writing Chunks length: %v", err)
	}
	for _, elem := range v.Chunks {
		if err := WriteChunk(w, elem); err != nil {
			return fmt.Errorf("error writing Chunks element: %v", err)
		}
	}
	if len(v.Trains) > 65535 {
		return fmt.Errorf("Trains slice too long: %d", len(v.Trains))
	}
	if err := binaryWrite(w, uint16(len(v.Trains))); err != nil {
		return fmt.Errorf("error writing Trains length: %v", err)
	}
	for _, elem := range v.Trains {
		if err := WriteTrain(w, elem); err != nil {
			return fmt.Errorf("error writing Trains element: %v", err)
		}
	}
	if len(v.Tracks) > 65535 {
		return fmt.Errorf("Tracks slice too long: %d", len(v.Tracks))
	}
	if err := binaryWrite(w, uint16(len(v.Tracks))); err != nil {
		return fmt.Errorf("error writing Tracks length: %v", err)
	}
	for _, elem := range v.Tracks {
		if err := WriteTrackUpdate(w, elem); err != nil {
			return fmt.Errorf("error writing Tracks element: %v", err)
		}
	}
	return nil
}

func ReadInitialLoadMessage(r io.Reader) (*InitialLoadMessage, error) {
	v := &InitialLoadMessage{}
	var WidthVal uint16
	if err := binaryRead(r, &WidthVal); err != nil {
		return nil, fmt.Errorf("error reading Width: %v", err)
	}
	v.Width = int(WidthVal)
	var HeightVal uint16
	if err := binaryRead(r, &HeightVal); err != nil {
		return nil, fmt.Errorf("error reading Height: %v", err)
	}
	v.Height = int(HeightVal)
	CameraPosVal, err := ReadPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading CameraPos: %v", err)
	}
	v.CameraPos = *CameraPosVal
	var ChunksLen uint16
	if err := binaryRead(r, &ChunksLen); err != nil {
		return nil, fmt.Errorf("error reading Chunks length: %v", err)
	}
	v.Chunks = make([]*world.Chunk, ChunksLen)
	for i := range v.Chunks {
		elem, err := ReadChunk(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Chunks element: %v", err)
		}
		v.Chunks[i] = elem
	}
	var TrainsLen uint16
	if err := binaryRead(r, &TrainsLen); err != nil {
		return nil, fmt.Errorf("error reading Trains length: %v", err)
	}
	v.Trains = make([]*trains.Train, TrainsLen)
	for i := range v.Trains {
		elem, err := ReadTrain(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Trains element: %v", err)
		}
		v.Trains[i] = elem
	}
	var TracksLen uint16
	if err := binaryRead(r, &TracksLen); err != nil {
		return nil, fmt.Errorf("error reading Tracks length: %v", err)
	}
	v.Tracks = make([]*TrackUpdate, TracksLen)
	for i := range v.Tracks {
		elem, err := ReadTrackUpdate(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Tracks element: %v", err)
		}
		v.Tracks[i] = elem
	}
	return v, nil
}
