// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"
)

func writeLoginMessage(w io.Writer, v *LoginMessage) error {
	if err := writeString(w, v.Username); err != nil {
		return fmt.Errorf("unable to serialize Username: %v", err)
	}
	return nil
}

func readLoginMessage(r io.Reader) (*LoginMessage, error) {
	v := &LoginMessage{}
	Username, err := readString(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Username: %v", err)
	}
	v.Username = Username
	return v, nil
}
