// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/world"
)

func writePos(w io.Writer, v *world.Pos) error {
	if v.X < 0 || v.X > 65535 {
		return fmt.Errorf("X out of uint16 range: %d", v.X)
	}
	if err := binaryWrite(w, uint16(v.X)); err != nil {
		return fmt.Errorf("error writing X: %v", err)
	}
	if v.Y < 0 || v.Y > 65535 {
		return fmt.Errorf("Y out of uint16 range: %d", v.Y)
	}
	if err := binaryWrite(w, uint16(v.Y)); err != nil {
		return fmt.Errorf("error writing Y: %v", err)
	}
	return nil
}

func readPos(r io.Reader) (*world.Pos, error) {
	v := &world.Pos{}
	var XVal uint16
	if err := binaryRead(r, &XVal); err != nil {
		return nil, fmt.Errorf("error reading X: %v", err)
	}
	v.X = int(XVal)
	var YVal uint16
	if err := binaryRead(r, &YVal); err != nil {
		return nil, fmt.Errorf("error reading Y: %v", err)
	}
	v.Y = int(YVal)
	return v, nil
}
