// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/world"
)

func writePos(w io.Writer, v *world.Pos) error {
	if err := binaryWrite(w, v.X); err != nil {
		return fmt.Errorf("error writing X: %v", err)
	}
	if err := binaryWrite(w, v.Y); err != nil {
		return fmt.Errorf("error writing Y: %v", err)
	}
	return nil
}

func readPos(r io.Reader) (*world.Pos, error) {
	v := &world.Pos{}
	if err := binaryRead(r, &v.X); err != nil {
		return nil, fmt.Errorf("error reading X: %v", err)
	}
	if err := binaryRead(r, &v.Y); err != nil {
		return nil, fmt.Errorf("error reading Y: %v", err)
	}
	return v, nil
}
