// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func WriteStation(w io.Writer, v *types.Station) error {
	if err := WritePos(w, &v.Pos); err != nil {
		return fmt.Errorf("error writing Pos: %v", err)
	}
	if v.Width < 0 || v.Width > 65535 {
		return fmt.Errorf("Width out of uint16 range: %d", v.Width)
	}
	if err := binaryWrite(w, uint16(v.Width)); err != nil {
		return fmt.Errorf("error writing Width: %v", err)
	}
	if v.Height < 0 || v.Height > 65535 {
		return fmt.Errorf("Height out of uint16 range: %d", v.Height)
	}
	if err := binaryWrite(w, uint16(v.Height)); err != nil {
		return fmt.Errorf("error writing Height: %v", err)
	}
	if err := writeString(w, v.Name); err != nil {
		return fmt.Errorf("unable to serialize Name: %v", err)
	}
	return nil
}

func ReadStation(r io.Reader) (*types.Station, error) {
	v := &types.Station{}
	PosVal, err := ReadPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Pos: %v", err)
	}
	v.Pos = *PosVal
	var WidthVal uint16
	if err := binaryRead(r, &WidthVal); err != nil {
		return nil, fmt.Errorf("error reading Width: %v", err)
	}
	v.Width = int(WidthVal)
	var HeightVal uint16
	if err := binaryRead(r, &HeightVal); err != nil {
		return nil, fmt.Errorf("error reading Height: %v", err)
	}
	v.Height = int(HeightVal)
	Name, err := readString(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Name: %v", err)
	}
	v.Name = Name
	return v, nil
}
