// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func WriteTile(w io.Writer, v *types.Tile) error {
	if err := WriteTileType(w, &v.Type); err != nil {
		return fmt.Errorf("error writing Type: %v", err)
	}
	return nil
}

func ReadTile(r io.Reader) (*types.Tile, error) {
	v := &types.Tile{}
	TypeVal, err := ReadTileType(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Type: %v", err)
	}
	v.Type = *TypeVal
	return v, nil
}
