// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"
)

func WriteTileUpdate(w io.Writer, v *TileUpdate) error {
	if err := WritePos(w, &v.Pos); err != nil {
		return fmt.Errorf("error writing Pos: %v", err)
	}
	if err := WriteTile(w, &v.Tile); err != nil {
		return fmt.Errorf("error writing Tile: %v", err)
	}
	return nil
}

func ReadTileUpdate(r io.Reader) (*TileUpdate, error) {
	v := &TileUpdate{}
	PosVal, err := ReadPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Pos: %v", err)
	}
	v.Pos = *PosVal
	TileVal, err := ReadTile(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Tile: %v", err)
	}
	v.Tile = *TileVal
	return v, nil
}
