// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"
)

func writeTileUpdate(w io.Writer, v *TileUpdate) error {
	if err := writePos(w, &v.Pos); err != nil {
		return fmt.Errorf("error writing Pos: %v", err)
	}
	if err := writeTile(w, &v.Tile); err != nil {
		return fmt.Errorf("error writing Tile: %v", err)
	}
	return nil
}

func readTileUpdate(r io.Reader) (*TileUpdate, error) {
	v := &TileUpdate{}
	PosVal, err := readPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Pos: %v", err)
	}
	v.Pos = *PosVal
	TileVal, err := readTile(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Tile: %v", err)
	}
	v.Tile = *TileVal
	return v, nil
}
