// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func WriteTileType(w io.Writer, v *types.TileType) error {
	if err := binaryWrite(w, uint8(*v)); err != nil {
		return fmt.Errorf("error writing TileType: %v", err)
	}
	return nil
}

func ReadTileType(r io.Reader) (*types.TileType, error) {
	var raw uint8
	if err := binaryRead(r, &raw); err != nil {
		return nil, fmt.Errorf("error reading TileType: %v", err)
	}
	v := types.TileType(raw)
	return &v, nil
}
