// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/types"
)

func writeTrack(w io.Writer, v *types.Track) error {
	if err := writeDir(w, &v.Direction); err != nil {
		return fmt.Errorf("error writing Direction: %v", err)
	}
	if err := binaryWrite(w, v.HasSignal); err != nil {
		return fmt.Errorf("error writing HasSignal: %v", err)
	}
	if err := writeDir(w, &v.SignalDir); err != nil {
		return fmt.Errorf("error writing SignalDir: %v", err)
	}
	if err := writeBlock(w, v.Block); err != nil {
		return fmt.Errorf("error writing Block: %v", err)
	}
	return nil
}

func readTrack(r io.Reader) (*types.Track, error) {
	v := &types.Track{}
	DirectionVal, err := readDir(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Direction: %v", err)
	}
	v.Direction = *DirectionVal
	if err := binaryRead(r, &v.HasSignal); err != nil {
		return nil, fmt.Errorf("error reading HasSignal: %v", err)
	}
	SignalDirVal, err := readDir(r)
	if err != nil {
		return nil, fmt.Errorf("error reading SignalDir: %v", err)
	}
	v.SignalDir = *SignalDirVal
	BlockVal, err := readBlock(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Block: %v", err)
	}
	v.Block = BlockVal
	return v, nil
}
