// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"
)

func WriteTrackUpdate(w io.Writer, v *TrackUpdate) error {
	if err := WritePos(w, &v.Pos); err != nil {
		return fmt.Errorf("error writing Pos: %v", err)
	}
	if err := WriteTrack(w, &v.Track); err != nil {
		return fmt.Errorf("error writing Track: %v", err)
	}
	return nil
}

func ReadTrackUpdate(r io.Reader) (*TrackUpdate, error) {
	v := &TrackUpdate{}
	PosVal, err := ReadPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Pos: %v", err)
	}
	v.Pos = *PosVal
	TrackVal, err := ReadTrack(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Track: %v", err)
	}
	v.Track = *TrackVal
	return v, nil
}
