// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/trains"
)

func writeTrainCar(w io.Writer, v *trains.TrainCar) error {
	if err := binaryWrite(w, v.X); err != nil {
		return fmt.Errorf("error writing X: %v", err)
	}
	if err := binaryWrite(w, v.Y); err != nil {
		return fmt.Errorf("error writing Y: %v", err)
	}
	if err := writeDir(w, &v.Direction); err != nil {
		return fmt.Errorf("error writing Direction: %v", err)
	}
	if err := writeCarType(w, &v.Type); err != nil {
		return fmt.Errorf("error writing Type: %v", err)
	}
	return nil
}

func readTrainCar(r io.Reader) (*trains.TrainCar, error) {
	v := &trains.TrainCar{}
	if err := binaryRead(r, &v.X); err != nil {
		return nil, fmt.Errorf("error reading X: %v", err)
	}
	if err := binaryRead(r, &v.Y); err != nil {
		return nil, fmt.Errorf("error reading Y: %v", err)
	}
	DirectionVal, err := readDir(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Direction: %v", err)
	}
	v.Direction = *DirectionVal
	TypeVal, err := readCarType(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Type: %v", err)
	}
	v.Type = *TypeVal
	return v, nil
}
