// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/trains"
)

func WriteTrainCar(w io.Writer, v *trains.TrainCar) error {
	if v.X < 0 || v.X > 65535 {
		return fmt.Errorf("X out of uint16 range: %d", v.X)
	}
	if err := binaryWrite(w, uint16(v.X)); err != nil {
		return fmt.Errorf("error writing X: %v", err)
	}
	if v.Y < 0 || v.Y > 65535 {
		return fmt.Errorf("Y out of uint16 range: %d", v.Y)
	}
	if err := binaryWrite(w, uint16(v.Y)); err != nil {
		return fmt.Errorf("error writing Y: %v", err)
	}
	if err := WriteDir(w, &v.Direction); err != nil {
		return fmt.Errorf("error writing Direction: %v", err)
	}
	if err := WriteCarType(w, &v.Type); err != nil {
		return fmt.Errorf("error writing Type: %v", err)
	}
	return nil
}

func ReadTrainCar(r io.Reader) (*trains.TrainCar, error) {
	v := &trains.TrainCar{}
	var XVal uint16
	if err := binaryRead(r, &XVal); err != nil {
		return nil, fmt.Errorf("error reading X: %v", err)
	}
	v.X = int(XVal)
	var YVal uint16
	if err := binaryRead(r, &YVal); err != nil {
		return nil, fmt.Errorf("error reading Y: %v", err)
	}
	v.Y = int(YVal)
	DirectionVal, err := ReadDir(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Direction: %v", err)
	}
	v.Direction = *DirectionVal
	TypeVal, err := ReadCarType(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Type: %v", err)
	}
	v.Type = *TypeVal
	return v, nil
}
