// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/trains"
)

func WriteTrain(w io.Writer, v *trains.Train) error {
	if err := writeUUID(w, &v.ID); err != nil {
		return fmt.Errorf("error writing ID: %v", err)
	}
	if err := binaryWrite(w, v.IsReversing); err != nil {
		return fmt.Errorf("error writing IsReversing: %v", err)
	}
	if err := binaryWrite(w, v.IsMoving); err != nil {
		return fmt.Errorf("error writing IsMoving: %v", err)
	}
	if err := binaryWrite(w, int32(v.Speed)); err != nil {
		return fmt.Errorf("error writing Speed: %v", err)
	}
	if err := binaryWrite(w, int32(v.Acceleration)); err != nil {
		return fmt.Errorf("error writing Acceleration: %v", err)
	}
	if err := WritePos(w, &v.Destination); err != nil {
		return fmt.Errorf("error writing Destination: %v", err)
	}
	if len(v.Cars) > 65535 {
		return fmt.Errorf("Cars slice too long: %d", len(v.Cars))
	}
	if err := binaryWrite(w, uint16(len(v.Cars))); err != nil {
		return fmt.Errorf("error writing Cars length: %v", err)
	}
	for _, elem := range v.Cars {
		if err := WriteTrainCar(w, elem); err != nil {
			return fmt.Errorf("error writing Cars element: %v", err)
		}
	}
	return nil
}

func ReadTrain(r io.Reader) (*trains.Train, error) {
	v := &trains.Train{}
	ID, err := readUUID(r)
	if err != nil {
		return nil, fmt.Errorf("error reading ID: %v", err)
	}
	v.ID = ID
	if err := binaryRead(r, &v.IsReversing); err != nil {
		return nil, fmt.Errorf("error reading IsReversing: %v", err)
	}
	if err := binaryRead(r, &v.IsMoving); err != nil {
		return nil, fmt.Errorf("error reading IsMoving: %v", err)
	}
	var SpeedVal int32
	if err := binaryRead(r, &SpeedVal); err != nil {
		return nil, fmt.Errorf("error reading Speed: %v", err)
	}
	v.Speed = int(SpeedVal)
	var AccelerationVal int32
	if err := binaryRead(r, &AccelerationVal); err != nil {
		return nil, fmt.Errorf("error reading Acceleration: %v", err)
	}
	v.Acceleration = int(AccelerationVal)
	DestinationVal, err := ReadPos(r)
	if err != nil {
		return nil, fmt.Errorf("error reading Destination: %v", err)
	}
	v.Destination = *DestinationVal
	var CarsLen uint16
	if err := binaryRead(r, &CarsLen); err != nil {
		return nil, fmt.Errorf("error reading Cars length: %v", err)
	}
	v.Cars = make([]*trains.TrainCar, CarsLen)
	for i := range v.Cars {
		elem, err := ReadTrainCar(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Cars element: %v", err)
		}
		v.Cars[i] = elem
	}
	return v, nil
}
