// Code generated by go generate; DO NOT EDIT.

package message

import (
	"fmt"
	"io"

	"github.com/danharasymiw/bit-rail/trains"
)

func writeWorldUpdateMessage(w io.Writer, v *WorldUpdateMessage) error {
	if len(v.TilesUpdated) > 65535 {
		return fmt.Errorf("TilesUpdated slice too long: %d", len(v.TilesUpdated))
	}
	if err := binaryWrite(w, uint16(len(v.TilesUpdated))); err != nil {
		return fmt.Errorf("error writing TilesUpdated length: %v", err)
	}
	for _, elem := range v.TilesUpdated {
		if err := writeTileUpdate(w, elem); err != nil {
			return fmt.Errorf("error writing TilesUpdated element: %v", err)
		}
	}
	if len(v.TracksUpdated) > 65535 {
		return fmt.Errorf("TracksUpdated slice too long: %d", len(v.TracksUpdated))
	}
	if err := binaryWrite(w, uint16(len(v.TracksUpdated))); err != nil {
		return fmt.Errorf("error writing TracksUpdated length: %v", err)
	}
	for _, elem := range v.TracksUpdated {
		if err := writeTrackUpdate(w, elem); err != nil {
			return fmt.Errorf("error writing TracksUpdated element: %v", err)
		}
	}
	if len(v.Trains) > 65535 {
		return fmt.Errorf("Trains slice too long: %d", len(v.Trains))
	}
	if err := binaryWrite(w, uint16(len(v.Trains))); err != nil {
		return fmt.Errorf("error writing Trains length: %v", err)
	}
	for _, elem := range v.Trains {
		if err := writeTrain(w, elem); err != nil {
			return fmt.Errorf("error writing Trains element: %v", err)
		}
	}
	return nil
}

func readWorldUpdateMessage(r io.Reader) (*WorldUpdateMessage, error) {
	v := &WorldUpdateMessage{}
	var TilesUpdatedLen uint16
	if err := binaryRead(r, &TilesUpdatedLen); err != nil {
		return nil, fmt.Errorf("error reading TilesUpdated length: %v", err)
	}
	v.TilesUpdated = make([]*TileUpdate, TilesUpdatedLen)
	for i := range v.TilesUpdated {
		elem, err := readTileUpdate(r)
		if err != nil {
			return nil, fmt.Errorf("error reading TilesUpdated element: %v", err)
		}
		v.TilesUpdated[i] = elem
	}
	var TracksUpdatedLen uint16
	if err := binaryRead(r, &TracksUpdatedLen); err != nil {
		return nil, fmt.Errorf("error reading TracksUpdated length: %v", err)
	}
	v.TracksUpdated = make([]*TrackUpdate, TracksUpdatedLen)
	for i := range v.TracksUpdated {
		elem, err := readTrackUpdate(r)
		if err != nil {
			return nil, fmt.Errorf("error reading TracksUpdated element: %v", err)
		}
		v.TracksUpdated[i] = elem
	}
	var TrainsLen uint16
	if err := binaryRead(r, &TrainsLen); err != nil {
		return nil, fmt.Errorf("error reading Trains length: %v", err)
	}
	v.Trains = make([]*trains.Train, TrainsLen)
	for i := range v.Trains {
		elem, err := readTrain(r)
		if err != nil {
			return nil, fmt.Errorf("error reading Trains element: %v", err)
		}
		v.Trains[i] = elem
	}
	return v, nil
}
